/*
 * Copyright (C) 2026 Ramiro Polla
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#include <stdio.h>

#include "libavutil/mem.h"
#include "libavutil/tree.h"
#include "libswscale/ops.h"
#include "libswscale/aarch64/ops.h"
#include "libswscale/ops_chain.h"

#ifdef _WIN32
#include <io.h>
#include <fcntl.h>
#endif

/*********************************************************************/
int main(int argc, char *argv[])
{
    struct AVTreeNode *root = NULL;
    int ret = 1;

#ifdef _WIN32
    _setmode(_fileno(stdout), _O_BINARY);
#endif

    SwsContext *ctx = sws_alloc_context();
    if (!ctx)
        goto fail;

    ret = ff_sws_enum_op_lists(ctx, &root, AV_PIX_FMT_NONE, AV_PIX_FMT_NONE,
                               ff_sws_collect_ops_aarch64);

    /**
     * Generate a C file with all the unique function parameter entries
     * collected by aarch64_enum_ops().
     */
    printf("/*\n");
    printf(" * This file is automatically generated. Do not edit manually.\n");
    printf(" * To regenerate, run: make sws_ops_entries_aarch64\n");
    printf(" */\n");
    printf("\n");
    printf("#define offsetof_exec_in       %zu\n", offsetof(SwsOpExec, in));
    printf("#define offsetof_exec_out      %zu\n", offsetof(SwsOpExec, out));
    printf("#define offsetof_exec_in_bump  %zu\n", offsetof(SwsOpExec, in_bump));
    printf("#define offsetof_exec_out_bump %zu\n", offsetof(SwsOpExec, out_bump));
    printf("#define offsetof_impl_cont     %zu\n", offsetof(SwsOpImpl, cont));
    printf("#define offsetof_impl_priv     %zu\n", offsetof(SwsOpImpl, priv));
    printf("#define sizeof_impl            %zu\n", sizeof(SwsOpImpl));
    printf("\n");
    av_tree_enumerate(root, stdout, NULL, ff_sws_op_print_aarch64);

fail:
    av_tree_destroy(root);
    sws_free_context(&ctx);
    return ret;
}
