name: Test aarch64 specific aspects

on:
  push:

# To enable this to run only on relevant pushes, we could add the
# following:
#    paths:
#    - '.github/workflows/aarch64.yml'
#    - '*/aarch64/*'

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test checkasm
        run: |
          sudo apt-get update && sudo apt-get install nasm
          mkdir build
          cd build
          ../configure --enable-gpl --samples=../samples
          make -j$(nproc)
          make -j$(nproc) fate-rsync
          make -j$(nproc) fate
          make -j$(nproc) run-checkasm

  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test checkasm
        run: |
          sudo apt-get update && sudo apt-get install qemu-user-static gcc-aarch64-linux-gnu
          mkdir build
          cd build
          ../configure --arch=aarch64 --cross-prefix=aarch64-linux-gnu- --target-os=linux --target-exec="qemu-aarch64-static -L /usr/aarch64-linux-gnu" --enable-gpl
          make -j$(nproc) run-checkasm

  linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and test checkasm
        run: |
          sudo apt-get update && sudo apt-get install qemu-user-static gcc-aarch64-linux-gnu clang
          mkdir build
          cd build
          ../configure --arch=aarch64 --cross-prefix=aarch64-linux-gnu- --target-os=linux --target-exec="qemu-aarch64-static -L /usr/aarch64-linux-gnu" --enable-gpl --cc="clang -target aarch64-linux-gnu"
          make -j$(nproc) run-checkasm

  linux-pacbti:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Fedora cross sysroot
        run: |
          # docker run --rm -v $PWD:/host arm64v8/fedora:35 bash -c "yum -y install glibc-devel gcc && tar -cf /host/fedora.tar /usr /etc/ld.so.cache"
          # This takes 14 minutes when run in QEMU, but takes 1 minute when run natively
          # on an actual aarch64 linux machine. Thus skip it and fetch a premade tarball
          # instead.
          curl -LO https://martin.st/temp/fedora35-aarch64-sysroot.tar.xz
          xz -d fedora*.tar.xz
          mkdir -p /opt/fedora-sysroot
          tar -C /opt/fedora-sysroot -xf fedora*.tar
          rm fedora*.tar
          ln -s usr/lib64 /opt/fedora-sysroot/lib64
          ln -s usr/lib /opt/fedora-sysroot/lib
      - uses: actions/checkout@v4
      - name: Build and test checkasm
        run: |
          sudo apt-get update && sudo apt-get install binutils-aarch64-linux-gnu clang
          # Using the QEMU installed by setup-qemu-action above, via binfmt, so no
          # --target-exec is needed, but point to the sysroot with QEMU_LD_PREFIX.
          export QEMU_LD_PREFIX=/opt/fedora-sysroot
          mkdir build
          cd build
          ../configure --arch=aarch64 --cross-prefix=aarch64-linux-gnu- --target-os=linux --cc="clang -target aarch64-linux-gnu" --sysroot=/opt/fedora-sysroot --extra-cflags="-mbranch-protection=standard" --extra-ldflags="-mbranch-protection=standard -Wl,-z,force-bti -L/opt/fedora-sysroot/usr/lib64 -L/opt/fedora-sysroot/usr/lib/gcc/aarch64-redhat-linux/11" --enable-gpl
          make -j$(nproc) run-checkasm

  linux-old-toolchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install an old toolchain
        run: |
          curl -LO https://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/aarch64-linux-gnu/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz
          tar -Jxf gcc-linaro-*.tar.xz
          rm gcc-linaro-*.tar.xz
          sudo mv gcc-linaro* /opt/gcc-linaro
          echo /opt/gcc-linaro/bin >> $GITHUB_PATH
      - name: Build and test checkasm
        run: |
          sudo apt-get update && sudo apt-get install qemu-user-static libc6-arm64-cross
          mkdir build
          cd build
          ../configure --arch=aarch64 --cross-prefix=aarch64-linux-gnu- --target-os=linux --target-exec="qemu-aarch64-static -L /usr/aarch64-linux-gnu" --enable-gpl
          make -j$(nproc) run-checkasm

  android-old-ndk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install an NDK
        run: |
          curl -LO https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
          unzip -q android-ndk-*.zip
          rm android-ndk-*.zip
          sudo mv android-ndk-* /opt/android-ndk
          echo /opt/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/*-x86*/bin >> $GITHUB_PATH
          sudo apt-get update && sudo apt-get install libtinfo5
      - name: Build
        run: |
          mkdir build
          cd build
          ../configure --arch=aarch64 --cc=aarch64-linux-android-gcc --cross-prefix=aarch64-linux-android- --target-os=android --enable-gpl --sysroot=/opt/android-ndk/platforms/android-28/arch-arm64 --extra-cflags="-isystem /opt/android-ndk/sysroot/usr/include -isystem /opt/android-ndk/sysroot/usr/include/aarch64-linux-android"
          make -j$(nproc) checkasm

  android-new-ndk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install an NDK
        run: |
          curl -LO https://dl.google.com/android/repository/android-ndk-r26c-linux.zip
          unzip -q android-ndk-*.zip
          rm android-ndk-*.zip
          sudo mv android-ndk-* /opt/android-ndk
          echo /opt/android-ndk/toolchains/llvm/prebuilt/*-x86*/bin >> $GITHUB_PATH
      - name: Build
        run: |
          mkdir build
          cd build
          ../configure --arch=aarch64 --cc=aarch64-linux-android34-clang --cross-prefix=llvm- --target-os=android --enable-gpl
          make -j$(nproc) checkasm

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Check host type
        run: |
          ARCH=$(uname -m)
          if [ "$ARCH" != "arm64" ]; then
              echo Unexpected host architecture $ARCH
              exit 1
          fi
      - name: Build and run all tests
        run: |
          mkdir build
          cd build
          ../configure --enable-gpl --samples=../samples
          make -j$(sysctl -n hw.ncpu)
          make -j$(sysctl -n hw.ncpu) fate-rsync
          make -j$(sysctl -n hw.ncpu) fate
          make -j$(sysctl -n hw.ncpu) run-checkasm

  msvc-wine:
    runs-on: ubuntu-latest
    container: linaro/wine-arm64
    steps:
      - name: Checkout msvc-wine
        uses: actions/checkout@v4
        with:
          repository: mstorsjo/msvc-wine
          ref: 00c2c606c33eb83bc40657aab964b280fe6b4f96
          path: msvc-wine
      - name: Install msvc-wine
        env:
          WINEPREFIX: /tmp/wine-x64-prefix
        run: |
          apt-get update && apt-get install -y --no-install-recommends wine python3 msitools ca-certificates winbind
          wine wineboot
          msvc-wine/vsdownload.py --accept-license --dest /opt/msvc
          msvc-wine/install.sh /opt/msvc
      - name: Checkout gas-preprocessor
        uses: actions/checkout@v4
        with:
          repository: ffmpeg/gas-preprocessor
          ref: 9309c67acb535ca6248f092e96131d8eb07eefc1
          path: gas-preprocessor
      - uses: actions/checkout@v4
        with:
          path: ffmpeg
      - name: Build
        env:
          WINEPREFIX: /tmp/wine-x64-prefix
        run: |
          apt-get update && apt-get install -y make gcc
          mkdir build
          cd build
          export PATH=$(pwd)/../gas-preprocessor:/opt/msvc/bin/arm64:$PATH
          ../ffmpeg/configure --arch=arm64 --target-os=win32 --toolchain=msvc --enable-cross-compile --enable-gpl --target-exec=wine-arm64
          make -j$(nproc) checkasm
      - name: Test checkasm
        run: |
          cd build
          make -j$(nproc) run-checkasm

  llvm-mingw:
    runs-on: ubuntu-latest
    container: linaro/wine-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Install llvm-mingw
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar -Jxf llvm-mingw-*-ucrt-ubuntu-*-x86_64.tar.xz
          rm llvm-mingw-*.tar.xz
          mv llvm-mingw-* /opt/llvm-mingw
          echo /opt/llvm-mingw/bin >> $GITHUB_PATH
      - name: Build and test checkasm
        run: |
          apt-get update && apt-get install -y make gcc
          mkdir build
          cd build
          ../configure --arch=aarch64 --target-os=mingw32 --cross-prefix=aarch64-w64-mingw32- --enable-gpl --target-exec=wine-arm64
          make -j$(nproc) run-checkasm

  msvc:
    runs-on: windows-latest
    steps:
      - name: Set up the environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64
      - name: Checkout gas-preprocessor
        uses: actions/checkout@v4
        with:
          repository: ffmpeg/gas-preprocessor
          ref: 9309c67acb535ca6248f092e96131d8eb07eefc1
          path: gas-preprocessor
      - uses: actions/checkout@v4
        with:
          path: ffmpeg
      - uses: msys2/setup-msys2@v2
        with:
          msystem: msys
          path-type: inherit
          install: >-
            make
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          export PATH=$(pwd)/../gas-preprocessor:$PATH
          ../ffmpeg/configure --arch=arm64 --target-os=win32 --toolchain=msvc --enable-cross-compile --enable-gpl
          make -j$(nproc) checkasm

  indent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check indentation
        run: |
          ./tools/check_arm_indent.sh
