# Based on Martin Storsjö's gha-aarch64 work
#
# .github/workflows/swscale.yml

name: Test swscale

on:
  push:

jobs:
  x86-llvm-mingw:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Install llvm-mingw and wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update && sudo apt-get install wine wine32
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar -Jxf llvm-mingw-*-ucrt-ubuntu-*-x86_64.tar.xz
          rm llvm-mingw-*.tar.xz
          sudo mv llvm-mingw-* /opt/llvm-mingw
          echo /opt/llvm-mingw/bin >> $GITHUB_PATH
      - name: Build and test swscale
        run: |
          mkdir build
          cd build
          ../configure --arch=x86 --target-os=mingw32 --cross-prefix=i686-w64-mingw32- --target-exec=wine
          make -j$(nproc) checkasm libswscale/tests/sws_ops.exe libswscale/tests/swscale.exe
          make V=1 -k fate-checkasm-sw_ops fate-sws-unscaled fate-sws-unstable || ret=$?
          for f in tests/data/fate/*.err; do [ -f "$f" ] && echo "=== $f ===" && cat "$f"; done
          exit ${ret:-0}
