# Based on Martin Storsjö's gha-aarch64 work
#
# .github/workflows/swscale.yml

name: Test swscale

on:
  push:

jobs:
  x86_64-linux-clang-ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build and test swscale
        run: |
          sudo apt-get update && sudo apt-get install nasm clang llvm libclang-rt-dev
          mkdir build
          cd build
          ../configure --cc=clang --cxx=clang++ --ld=clang --extra-cflags='-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=undefined' --extra-ldflags='-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=undefined'
          make -j$(nproc) checkasm libswscale/tests/sws_ops libswscale/tests/swscale
          make V=1 -k fate-checkasm-sw_ops fate-sws-unscaled fate-sws-unstable || ret=$?
          for f in tests/data/fate/*.err; do [ -f "$f" ] && echo "=== $f ===" && cat "$f"; done
          exit ${ret:-0}

  aarch64-linux-clang-ubsan:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - name: Build and test swscale
        run: |
          sudo apt-get update && sudo apt-get install clang llvm libclang-rt-dev
          mkdir build
          cd build
          ../configure --cc=clang --cxx=clang++ --ld=clang --extra-cflags='-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=undefined' --extra-ldflags='-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=undefined'
          make -j$(nproc) checkasm libswscale/tests/sws_ops libswscale/tests/swscale
          make V=1 -k fate-checkasm-sw_ops fate-sws-unscaled fate-sws-unstable || ret=$?
          for f in tests/data/fate/*.err; do [ -f "$f" ] && echo "=== $f ===" && cat "$f"; done
          exit ${ret:-0}
