clean::
	$(RM) $(CLEANSUFFIXES:%=fftools/graph/%)

GRAPHPRINT-OBJS += fftools/graph/graphprint.css.min.res.o
GRAPHPRINT-OBJS += fftools/graph/graphprint.html.res.o
GRAPHPRINT-OBJS += fftools/graph/graphprint.o

RESOBJS += $(filter %.res.o,$(GRAPHPRINT-OBJS))
